# -*- coding: utf-8 -*-
"""PredictAppleStockPrice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kJw3Rzho9eiawpOiR7unA_EqbQt3IbvJ
"""

# Import the kibraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Load the Stock Data
file_path = 'AAPL.csv'
historical_data = pd.read_csv(file_path, parse_dates = ['Date'])
historical_data.set_index('Date', inplace=True)
print(historical_data)

# Calculate the starting prices, mu and sigma
starting_price = historical_data['Close'].iloc[-1]
daily_returns = historical_data['Close'].pct_change().dropna()
mu = daily_returns.mean() * 252
sigma = daily_returns.std() * np.sqrt(252)

# Create the Monte Carlo parameters
num_simulations = 1000
num_days = 252
dates = pd.date_range(start = historical_data.index[-1], periods = num_days + 1, freq = 'B')

# Create the simulation array
simulations = np.zeros((num_simulations, num_days))

# Create the Monte Carlo simulation
for i in range(num_simulations):
  daily_returns_simulated = np.random.normal(mu/num_days, sigma/np.sqrt(num_days), num_days)
  price_path = starting_price * np.cumprod(1+daily_returns_simulated)
  simulations[i, :] = price_path

# Show simulations
simulations

# Calculate the expected price after 252 traiding days
expected_price = simulations[:, -1].mean()
print('Expected price:', expected_price)

historical_data.iloc[-1]

from matplotlib.lines import lineStyles
# Plot the simulations
plt.figure(figsize = (12,8))
for i in range(0, num_simulations):
  plt.plot(dates[1:], simulations[i], alpha = 0.5, color = np.random.rand(3,))

plt.xlabel('Dates')
plt.ylabel('Close price')
plt.title('Monte Carlo Simulation for Apple Stock')
plt.gca().set_facecolor('pink')
plt.grid(color = 'navy', linestyle = '--', linewidth = 0.5)
plt.tick_params(color = 'black')
plt.show()